In [11]:
import numpy as np



In [12]:
row1 = np.array([8.0, 6.0, 4.0, 2.0, 0.0, -2.0, -4.0, -6.0, -8.0])
print(row1)


[ 8.  6.  4.  2.  0. -2. -4. -6. -8.]


In [13]:
row2 = np.linspace(-16.0, 16.0, 9)
#9 werte von -16 bis 16
print(row2)


[-16. -12.  -8.  -4.   0.   4.   8.  12.  16.]


In [14]:
row3 = np.arange(-1.2, 1.3, 0.3)
#Wichtig: np.arange() geht nie bis zur letzten Zahl, sondern nur bis kurz davor – deshalb schreiben wir 1.3, obwohl wir 1.2 als letzte Zahl wollen.
print(row3)


[-1.2 -0.9 -0.6 -0.3  0.   0.3  0.6  0.9  1.2]


In [19]:
print("Matrix A:\n", A)

print("\nMatrix B:\n", B)


Matrix A:
 [[  8.0   6.0   4.0   2.0   0.0  -2.0  -4.0  -6.0  -8.0]
 [-16.0 -12.0  -8.0  -4.0   0.0   4.0   8.0  12.0  16.0]
 [ -1.2  -0.9  -0.6  -0.3   0.0   0.3   0.6   0.9   1.2]]

Matrix B:
 [[ 4.0  0.0 -4.0]
 [-0.6  0.0  0.6]]


In [17]:
import numpy as np

# Erste Zeile manuell mit np.array (wie vorgegeben)
row1 = np.array([8.0, 6.0, 4.0, 2.0, 0.0, -2.0, -4.0, -6.0, -8.0])

# Zweite Zeile mit np.linspace: von -16 bis 16, 9 Werte → gleichmäßige Abstände
row2 = np.linspace(-16.0, 16.0, 9)

# Dritte Zeile mit np.arange: von -1.2 bis inkl. 1.2 in Schritten von 0.3
row3 = np.arange(-1.2, 1.3, 0.3)  # np.arange schließt das Ende nicht ein, daher bis 1.3

# Matrix A zusammenbauen: jede Zeile als eigene Zeile
A = np.array([row1, row2, row3])

# Einmal kontrollieren:
print("Matrix A:")
print(A)

# Jetzt: B = 2×3 Matrix aus Zeile 1 und 3 (Index 0 und 2),
# und den Spalten 3., 5. und 7. (Index 2, 4, 6)
#B = A[[0, 2], [2, 4, 6]]

# Aber Achtung: Das liefert flache Arrays. Für 2x3 Matrix:
B = A[[0, 2], :][:, [2, 4, 6]]  # 🟢 Korrekte 2x3 Matrix per Slicing

# Ausgabe
print("\nMatrix B:")
print(B)


Matrix A:
[[  8.    6.    4.    2.    0.   -2.   -4.   -6.   -8. ]
 [-16.  -12.   -8.   -4.    0.    4.    8.   12.   16. ]
 [ -1.2  -0.9  -0.6  -0.3   0.    0.3   0.6   0.9   1.2]]

Matrix B:
[[ 4.   0.  -4. ]
 [-0.6  0.   0.6]]
