In [1]:
import numpy as np

# Erste Zeile mit np.array()
row1 = np.array([-1.2, -0.9, -0.6, -0.3, 0.0, 0.3, 0.6, 0.9, 1.2])

# Zweite Zeile mit np.linspace()
row2 = np.linspace(-16.0, 16.0, 9)

# Dritte Zeile mit np.arange()
row3 = np.arange(8.0, -9.0, -2.0)

# Matrix A zusammensetzen
A = np.array([row1, row2, row3])


# Ausgabeformat anpassen
np.set_printoptions(precision=1, suppress=True, floatmode='fixed')
print("Matrix A:")
print(A)

# Matrix B extrahieren: Zeilen 2 & 3 (Index 1, 2) und Spalten 2., 5., 8. (Index 1, 4, 7)

B = A[[1, 2], :][:, [1, 4, 7]]

print("\nMatrix B:")
print(B)



Matrix A:
[[ -1.2  -0.9  -0.6  -0.3   0.0   0.3   0.6   0.9   1.2]
 [-16.0 -12.0  -8.0  -4.0   0.0   4.0   8.0  12.0  16.0]
 [  8.0   6.0   4.0   2.0   0.0  -2.0  -4.0  -6.0  -8.0]]

Matrix B:
[[-12.0   0.0  12.0]
 [  6.0   0.0  -6.0]]
