<img src="images/00-mathematics_with_python.png" style="height:250px" align="left">

<!--NAVIGATION-->
< [II Python Packages](20-python_packages.ipynb) | [2 Matplotlib](22-matplotlib.ipynb) >

# 1 Numpy
NumPy integrates the numerical power of C or Fortran into Python. The syntax, especially for matrix calculations, is much simpler and more compact and is oriented towards Matlab.

In [3]:
import numpy as np
print(np.__version__)

2.2.3


## 1.1 Creating arrays
Use square brackets [...] to create arrays.

In [4]:
a=np.array([47.0,11.0,0.0,8.0,15.0])
print(a)

[47. 11.  0.  8. 15.]


Nested square brackets generate arrays with higher dimensions.

In [5]:
A=np.array([[1.0,2.0],[3.0,4.0]])
print(A)

[[1. 2.]
 [3. 4.]]


The type of an array may be specified.

In [6]:
np.array([47.0,11.0,0.0,8.0,15.0],dtype=int)

array([47, 11,  0,  8, 15])

<div class="alert alert-block alert-danger">
The function `arange(start,stop,step)` generates a sequence of numbers starting with `start` ending bevore `stop` with step size `step`, see
</div>

https://numpy.org/devdocs/reference/generated/numpy.arange.html.

In [7]:
start = 0.0
stop = 1.0
step = 0.2
x=np.arange(start,stop+step,step)
print(x)

[0.  0.2 0.4 0.6 0.8 1. ]


<div class="alert alert-block alert-danger">
The function `linspace(start,stop,num)` generates a sequence off numbers starting with `start` ending at `stop` with `num` numberts of steps, see
</div>

https://numpy.org/devdocs/reference/generated/numpy.linspace.html

In [8]:
start = 0.0
stop = 1.0
num = 5
y=np.linspace(start,stop,num)
print(y)

[0.   0.25 0.5  0.75 1.  ]


## 1.2 Indexing
The indices start with index $0$.

In [9]:
a[0]

np.float64(47.0)

In order to adress elements from the end use negative indices.

In [10]:
a[-1]

np.float64(15.0)

First index is used for rows and second index for columns. 

In [11]:
A[1,0]

np.float64(3.0)

## 1.3 Slicing
Slicing means cutting out peaces of data.

In [12]:
B=np.array([[10.0,11.0,12.0,13.0,14.0,15.0],[20.0,21.0,22.0,23.0,24.0,25.0]])
print(B)

[[10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]


`:` is used to select all elements in a row or colum.

In [13]:
B[1,:]

array([20., 21., 22., 23., 24., 25.])

`start:end` is used to select all elements with indices between `start` and `end`.

In [14]:
B[0,1:4]

array([11., 12., 13.])

`start:end:stepsize` is used to select all elements with indices between `start` and `end`, proceeding with step size `stepsize`.

In [15]:
B[0,1:4:2]

array([11., 13.])

## Mathematical functions
The usual mathematical functions may be used for all elements of an array. 

$
\begin{array}{|l|l|l|l|l|}
\hline
\mbox{sin} & \mbox{cos} & \mbox{tan} \\
\hline
\mbox{arcsin} & \mbox{arccos} & \mbox{arctan} \\
\hline
\end{array}
$

In [16]:
x = np.array([0.0,np.pi/6.0,np.pi/4.0,np.pi/3,np.pi/2])
print(np.sin(x))
print(np.cos(x))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


## Division by zero
A division by zero will result in `inf` or `nan`.

In [17]:
np.array([1.0,0.0])/0.0


C:\Users\adam8\AppData\Local\Temp\ipykernel_27060\3292526706.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([1.0,0.0])/0.0
C:\Users\adam8\AppData\Local\Temp\ipykernel_27060\3292526706.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([1.0,0.0])/0.0


array([inf, nan])


## Literature
- https://numpy.org
- https://numpy.org/devdocs/user/quickstart.html
- https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html
- https://www.youtube.com/embed/GB9ByFAIAH4